### ISSUE TITLE
Development workflow in the abstract

### ISSUE THREAD

**Issue by kekoziar** [devnich/project-management#3]
I'm not sure of how you will talk going from one topic to the next, but the flow in this section seems weird.  I think it's the language section in the middle of the abstract concept.  Will it work at the beginning of the section?  *Your workflow and available tools are also dependent on the language you're using, so let's talk about that for a minute before diving into more specifics.*  

I think the language section jumps out at me because it is even more abstract than the list of questions for developing your workflow.

**Comment by devnich** [comment]
This is good.
