### ISSUE TITLE
Comments for Derek.

### ISSUE THREAD

**Issue by JoeAmeen** [devnich/project-management#5]
Derek, 

These are just a few things I saw. Feel free to disregard. Per our conversation, I'm not overly familiar with this sort of documentation. 

-Maybe a softer intro sentence. Or a short preamble leading into the content. 
-Some of the numbered or bulleted lists could use some exposition. 

General Project Management > What kind of project do you have?
This section might benefit from a few short examples to give the list context. 

-In Concrete project planning, DMP is not defined. 

-In the section on choosing a language the first sentence should have "...are dependent..." instead of "...are depend..."

**Comment by PLNReynolds** [comment]
Thanks for the feedback! 

"depend" typo fixed
DMP defined and resource linked
