### ISSUE TITLE
Suggested Images

### ISSUE THREAD

**Issue by kekoziar** [devnich/project-management#6]
Introduction: https://xkcd.com/292/

**Comment by kekoziar** [comment]
project planning: https://geekandpoke.typepad.com/geekandpoke/2012/01/simply-explained-dp.html

**Comment by kekoziar** [comment]
maybe use one panel of this to side with your abstract sections? https://geek-and-poke.com/geekandpoke/2014/12/22/developers

**Comment by kekoziar** [comment]
I like these two, but not sure where they can go
https://xkcd.com/844/
https://xkcd.com/1319/

**Comment by kekoziar** [comment]
scheduling: https://phdcomics.com/comics/archive.php?comicid=1687

**Comment by kekoziar** [comment]
I'm not sure where this might fit, but I definitely want to use it somehow for my swc workshops: https://bonkersworld.net/apparent-complexity

**Comment by PLNReynolds** [comment]
Found spots to add all (except abstract and apparent-complexity comics).

**Comment by kekoziar** [comment]
thanks.  I'll close the issue.
